// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hQQOPOOOOOO'#Ce'#CeQ]OPO'#ChOhOQO'#ChOpOPO'#CiOOOO'#Cg'#CgOOOO'#Cd'#CdQQOPOOOOOO-E6c-E6cO{OQO,59SO!TOPO,59TOOOO,59S,59SO!OOPO,59SO!`OPO,59TOOOO,59T,59TO!kOPO,59TOOOO-E6b-E6bOOOO1G.n1G.nO!sOPO1G.nO!xOPO1G.oOOOO1G.o1G.oO#TOPO1G.oO#TOPO1G.oOOOO7+$Y7+$YOOOO7+$Z7+$ZO#]OPO7+$ZOOOO<<Gu<<Gu",
  stateData: "#e~OQPORROUSO~OQPORXOUYO~OS[OTZO~OQPORROV^O~OSbOTaO~OQPORROVdO~OQPORXOVdO~OQPOVdO~OTgO~OQPORXOVhO~OQPOVhO~OQPOVjO~O",
  goto: "!`^PPPPPPPP_eP|!Q![QVOR`VSQOVYWQ]cfiQ]SQcYQf_RieTUOVSTOVQ_SReYTTOV",
  nodeNames: "⚠ program SPACE CONTENT_BEGIN CONTENT CONTENT_CLOSE WRITE_OPEN WRITE_CLOSE",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "(d~RbOX!ZXY$aYZ$aZ]!Z]^$a^p!Zpq$aq!}!Z!}#O%d#O#P!Z#P#Q&Q#Q#o!Z#o#p&n#p#q!Z#q#r'i#r;'S!Z;'S;=`#h<%lO!ZQ!`VSQO#o!Z#o#p!u#p#q!Z#q#r#n#r;'S!Z;'S;=`#h<%lO!ZQ!xTO#o!Z#o#p#X#p;'S!Z;'S;=`#h<%lO!ZQ#[SO#o!Z#p;'S!Z;'S;=`#h<%lO!ZQ#kP;=`<%l!ZQ#qTO#q!Z#q#r$Q#r;'S!Z;'S;=`#h<%lO!ZQ$TSO#q!Z#r;'S!Z;'S;=`#h<%lO!ZR$h^SQQPOX!ZXY$aYZ$aZ]!Z]^$a^p!Zpq$aq#o!Z#o#p!u#p#q!Z#q#r#n#r;'S!Z;'S;=`#h<%lO!ZR%kVSQUPO#o!Z#o#p!u#p#q!Z#q#r#n#r;'S!Z;'S;=`#h<%lO!ZR&XVSQVPO#o!Z#o#p!u#p#q!Z#q#r#n#r;'S!Z;'S;=`#h<%lO!Z~&qTO#o!Z#o#p'Q#p;'S!Z;'S;=`#h<%lO!Z~'TTO#o!Z#o#p'd#p;'S!Z;'S;=`#h<%lO!Z~'iOR~~'lTO#q!Z#q#r'{#r;'S!Z;'S;=`#h<%lO!Z~(OTO#q!Z#q#r(_#r;'S!Z;'S;=`#h<%lO!Z~(dOT~",
  tokenizers: [0, 1],
  topRules: {"program":[0,1]},
  tokenPrec: 0
})
