// This file was generated by lezer-generator. You probably shouldn't edit it.
export const program = 1,
	SPACE = 2,
	CONTENT_BEGIN = 3,
	CONTENT = 4,
	CONTENT_CLOSE = 5,
	WRITE_OPEN = 6,
	WRITE_CLOSE = 7;
